### ISSUE TITLE
Non Printable Charaters

### ISSUE THREAD

**Issue by Techone001** [Zayik/CommandSender#10]
Is there a way to send Non printable characters?, I am looking for Line feed.

**Comment by Zayik** [comment]
Thanks for your patience. Been a hectic couple of days. 

I have added an update that will allow you to send ascii characters, which encompass the good ole Line Feed. 

You will have to use its Html number notation, as the Plugin uses Html for its presentation. 
You can find the value representation here: 
https://www.ascii-code.com/

Line Feed = &#010;

Use case: 
![image](https://user-images.githubusercontent.com/8930730/184068047-15bdc376-a400-4b0d-92c2-5d0c3fc946cd.png)
