### ISSUE TITLE
Need Documentation of Example Commands

### ISSUE THREAD

**Issue by Jinx-IT** [Zayik/CommandSender#12]
Need documented examples of how to format the commands.  Straightforward ASCII commands are sending but not working.

**Comment by Zayik** [comment]
I have updated the documentation to include some examples of how to make that translation.

**Comment by Zayik** [comment]
I just submitted a new build that should change how the encoding of the string works. Grab the latest and try your original command with \r

**Comment by Jinx-IT** [comment]
This is exciting!  I’ll try this today.  Do I need to delete the plugin from stream deck and re-install it, thusly having to recreate my buttons, or can I just install this one over the top of the old one?


Sincerely,

Destry Jinks Sr.
***@***.******@***.***>
407.574.6978
[jinxITsignature1]

**Comment by Zayik** [comment]
I think you can just reinstall the plug in. If you have to uninstall, it
shouldn't remove the buttons and should be available after installing
latest version.

**Comment by Jinx-IT** [comment]
Unfortunately I now get warning triangles with the new version.  Even tried recreating buttons.  I went back to the original release, and using the string you sent me in the initial clarification does send a command, but it isn’t acknowledged…so that’s still not correct.

Happy to help troubleshoot this with you.  If you want me to make a button and send commands to you I can, just give me an IP and port.


Sincerely,

Destry Jinks Sr.
***@***.******@***.***>
407.574.6978
[jinxITsignature1]
