### ISSUE TITLE
Wiz Bulb

### ISSUE THREAD

**Issue by josefalk** [Zayik/CommandSender#15]
This command sender works well with Wiz Bulb
example usage 
Communication type: UDP
IP: IP
Port: 38899
Command Pressed: {"id":1,"method":"setState","params":{"state":true}}

One room can contain several lights ( I have 10+) so I need the ability to add several IP addresses for the same command. The extension cal currently sends one command for one button.
Thanks for help and support.

**Comment by Zayik** [comment]
Hey there. I apologize for the late reply as it's been quite hectic at work
as of late.

Did you need to also specify a different port for each ip address?
If that is acceptable, it shouldn't be too much effort to update it to be
something like
IP: IP1; IP2; IP3
Port: 38899

In the meantime, Steam Deck does support a MultiAction button so one press
can activate multiple commands.



[image: image.png]

[image: image.png]


[image: image.png]

**Comment by josefalk** [comment]
Thank you for your reply. They are in the same port, so like you said:
IP: IP1; IP2; IP3
Port: 38899
It will be great if you update it.

regarding multi-action, it works a bit differently
in multi-action:
it is applying to both press and release when you release. so it is not actual.
means in multi-action, I configure several commands from your extension, I press the button and stay (nothing happens) then release the button, and the bulb turns on and off immediately (an example).

in your extension:
You press the button, and the press action happens. release the button then the release action happens. 
That might be another fix?

the images did not show up.

Thanks a lot.
Best regards 
Josef

**Comment by Zayik** [comment]
I have created a pre-release to test this new feature. 
https://github.com/Zayik/CommandSender/releases/tag/v1.1.0

Under IpAddress, add multiple of them separated by a semicolon
Example: 127.0.0.1;127.0.0.2

Please give this a try and let me know how that works.
