### ISSUE TITLE
Multi Action 

### ISSUE THREAD

**Issue by nooonde2** [Zayik/CommandSender#3]
Hi,
is it possible to set an udp-command in the "Multi Action Window"? I can't see the option there,

**Comment by achanner** [comment]
+1 for this.

The UDP send functionality works an absolute treat for what I need (Thanks BiffMasterZay!) but I would love to be able to send messages in Streamdeck as part of a Multi-Action command - is it possible that you can add this option please?

**Comment by Zayik** [comment]
Glad to hear that send functionality is working great for you!

I'll have to look into this. At first glance, I don't see anything that would be preventing it from showing up. Unfortunately, the developer documentation doesn't appear to have much information regarding upgrading a plugin to have multi-action support so it will take some research when I have a chance.

**Comment by achanner** [comment]
> I'll have to look into this. At first glance, I don't see anything that would be preventing it from showing up. Unfortunately, the developer documentation doesn't appear to have much information regarding upgrading a plugin to have multi-action support so it will take some research when I have a chance.

Completely understand - best of luck and thanks for the plugin - Im amazed there doesnt seem to be any simple send UDP tool for streamdeck out there, and yours worked an absolute treat first time!

**Comment by Zayik** [comment]
Part of the issue is that Javascript by default doesn't work with udp, at
least not with streamdeck. So that's an entry barrier for making udp
related apps. I think there exist js libraries for using udp but they are
not accessible using stream deck.  Luckily somebody made a library for
using c# which fully supported udp and thats what I used. I might try to
look at it tonight or tomorrow.

**Comment by gaffatejp** [comment]
It is not enough to just set the multi action support flag to true in the manifest file?

**Comment by gaffatejp** [comment]
Yup, it's that simple. Just change to `"SupportedInMultiActions": true` in the manifestfile, and it works with multi action buttons. I tested it with a receiver to make sure. Note: You have to download the project, change the manifest file, build in Visual Studio, run CreatePackageInstaller.bat, then install the plugin.

**Comment by Zayik** [comment]
Hey gaffatejp,

Thanks for sending back your findings. I lowkey forgot about this after spending quite a few 10-12hr+ days of work. I'm going to set a reminder to get this updated after work today. 

Thanks again and hope it's working out well for you. If you have any feedback, please let me know and I can look at adding features to it if needed.

**Comment by Zayik** [comment]
An update has been made and the easy installer updated. Multi Action now operational!
![image](https://user-images.githubusercontent.com/8930730/157998274-bd071ddb-7459-4649-9252-c46ab69b5fa8.png)
