### ISSUE TITLE
Toggle Button

### ISSUE THREAD

**Issue by formulynx** [Zayik/CommandSender#4]
Hi @Zayik,
Is it possible for this plugin to make a button togglable, or have on/off state?
There is already a press/release function, but I want specific state to be hold when pressed once.
Thank you for developing great plugin!

**Comment by Zayik** [comment]
Hey @formulynx, thanks for the kind words and your patience with me getting back to you. I just got back from being out of town for a memorial service and was thinking about this. 

What I could do is make it so you can set a number of states, and when you press the button, it cycles between them. 

So you could do
State 1:
Command Pressed 1
Command Released 1

State 2: 
Command Pressed 2
Command Released 2

It starts at state 1. When you press the button, it sends the "Command Pressed 1" and "Command Released 1". Then it moves to state 2. Then to state 3, etc, until the end, then goes back to state 1. 

So your case, you just leave state 2 empty. (Current behavior is leaving the 'Command Pressed/Released' empty won't attempt to send any udp packets.)

I think this should fulfill your needs while also allowing it to be a bit more powerful for users who want to have a multitude of states.

**Comment by formulynx** [comment]
Hi @Zayik, thanks for your great suggestion!
Sounds perfect to me, and cycling through multiple states are much better than my proposal.
I'm looking forward to see and try the update.

**Comment by Zayik** [comment]
Hey there. I've updated the tool and it now includes states up to 10. You can select how many desired states and it will autoupdate your view of states. 

In your use case, just leave set desired states to 2, and leave the command pressed and command released empty. 

I'm going to look into being able to autoupdate the icon to make it easier to see which state is currently selected. 

Enjoy!

**Comment by Zayik** [comment]
Now also had number value to indicate state it is in. Starts at 0 and goes to 9.
