### ISSUE TITLE
Multiple states only show State0 after next time you open the setting

### ISSUE THREAD

**Issue by formulynx** [Zayik/CommandSender#5]
Hi @Zayik, thank you very much for adding multiple states to the plugin!
However, I found a bug so I will report it below.

**How to reproduce:**

1. Setup multiple states (set Desired States more than 2)
The input forms for the number of states are shown under the states section

2. After your states are all set, click other button to open other settings
3. Then come back to the button you set with CommandSender
4. Even your states are set more than 2, only State0 is shown
5. Change the "Desire States" to other number, then all your parameter sets are shown

So, the states are properly saved and works perfectly,
but the input forms for state1 and latter are not shown when you open the setting next time.

For now I can workaround with procedure 5, so this bug is not an urgent one.
I will really appreciate it if you have time to look in to this.
Thank you again for your great work!

**Comment by Zayik** [comment]
Hey there, thanks for the heads up and the very detailed steps to reproduce. I had saw that and thought I had got that part fixed, but looks like my attempted fix didn't fly xD

Will try to get a bug fix by end of this weekend.

**Comment by Zayik** [comment]
I've found a solution and uploaded the latest. Enjoy!
